#!/bin/bash

CONFIG_DIR="$HOME/.config/s3config"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# Function to create paths if not exists
create_paths() {
    mkdir -p "$1"
}

# Function to write aws config and credentials
write_aws_config() {
    local config="$1"
    mkdir -p ~/.aws
    # Start files
    > ~/.aws/config
    > ~/.aws/credentials

    # Iterate over each remote
    echo "$config" | yq eval '.remotes | keys' - | while IFS= read -r remote; do
        if [ -n "$remote" ]; then
            remote=$(echo "$remote" | sed 's/^- //')  # Remove prefix from list
            access_key=$(echo "$config" | yq eval ".remotes.\"$remote\".access_key" -)
            secret_key=$(echo "$config" | yq eval ".remotes.\"$remote\".secret_key" -)
            region=$(echo "$config" | yq eval ".remotes.\"$remote\".region" -)
            endpoint=$(echo "$config" | yq eval ".remotes.\"$remote\".endpoint" -)
            request_checksum_calculation=$(echo "$config" | yq eval ".remotes.\"$remote\".request_checksum_calculation" -)
            response_checksum_validation=$(echo "$config" | yq eval ".remotes.\"$remote\".response_checksum_validation" -)
            host=$(echo "$config" | yq eval ".remotes.\"$remote\".host" -)

            # Write config
            {
                echo "[profile $remote]"
                echo "endpoint_url = $endpoint"
                echo "region = ${region:-us-east-1}"
                # Only write `request_checksum_calculation` if it's not null or missing
                if [ "$request_checksum_calculation" != "null" ] && [ -n "$request_checksum_calculation" ]; then
                    echo "request_checksum_calculation = $request_checksum_calculation"
                fi

                # Only write `response_checksum_validation` if it's not null or missing
                if [ "$response_checksum_validation" != "null" ] && [ -n "$response_checksum_validation" ]; then
                    echo "response_checksum_validation = $response_checksum_validation"
                fi
                echo "s3 ="
                echo "    addressing_style = ${host:-path}"
                echo
            } >> ~/.aws/config

            # Write credentials
            {
                echo "[$remote]"
                echo "aws_access_key_id = $access_key"
                echo "aws_secret_access_key = $secret_key"
                echo
            } >> ~/.aws/credentials
        fi
    done
    echo 'write aws config e credentials'
}

# Function to write rclone config
write_rclone_config() {
    local config="$1"
    mkdir -p ~/.config/rclone
    # Start file
    > ~/.config/rclone/rclone.conf

    # Iterate over each remote
    echo "$config" | yq eval '.remotes | keys' - | while IFS= read -r remote; do
        if [ -n "$remote" ]; then
            remote=$(echo "$remote" | sed 's/^- //')  # Remover prefixo de lista
            access_key=$(echo "$config" | yq eval ".remotes.\"$remote\".access_key" -)
            secret_key=$(echo "$config" | yq eval ".remotes.\"$remote\".secret_key" -)
            region=$(echo "$config" | yq eval ".remotes.\"$remote\".region" -)
            endpoint=$(echo "$config" | yq eval ".remotes.\"$remote\".endpoint" -)

            # Write rclone.conf
            {
                echo "[$remote]"
                echo "type = s3"
                echo "provider = Other"
                echo "access_key_id = $access_key"
                echo "secret_access_key = $secret_key"
                echo "region = ${region:-us-east-1}"
                echo "endpoint = $endpoint"
                echo
            } >> ~/.config/rclone/rclone.conf
        fi
    done
    echo 'write rclone.conf'
}

# Function to write mgc auth
write_mgc_configs() {
    # Process each remote in the YAML file
    local config="$1"
    echo "$config" | yq eval '.remotes | keys' - | while IFS= read -r remote; do
        remote=$(echo "$remote" | sed 's/^- //')  # Remove prefix from list
        remote_folder="$HOME/.config/mgc/$remote"
        create_paths "$remote_folder"

        access_key=$(echo "$config" | yq eval ".remotes.\"$remote\".access_key" -)
        secret_key=$(echo "$config" | yq eval ".remotes.\"$remote\".secret_key" -)
        region=$(echo "$config" | yq eval ".remotes.\"$remote\".region" -)

        echo "access_key_id: $access_key" > "${remote_folder}/auth.yaml"
        echo "secret_access_key: $secret_key" >> "${remote_folder}/auth.yaml"

        echo "region: ${region:-us-east-1}" > "${remote_folder}/cli.yaml"
    done

    echo 'write mgc auth'
}

# Function to configure a new profile
profile_configure() {
    read -rp "Enter profile name: " profile_name
    read -rp "Enter access key: " access_key
    read -rp "Enter secret key: " secret_key
    read -rp "Enter endpoint: " endpoint
    read -rp "Enter region (default us-east-1): " region
    read -rp "Enter request_checksum_calculation (default WHEN_REQUIRED): " request_checksum_calculation
    read -rp "Enter response_checksum_validation (default WHEN_REQUIRED): " response_checksum_validation
    read -rp "Enter host style (default path): " host_style

    # Use "us-east-1" with default region if not send
    region=${region:-us-east-1}
    host_style=${host_style:-path}
    # Append new remote to file config.yaml
    yq eval -i ".remotes.\"$profile_name\" = {\"access_key\": \"$access_key\", \"secret_key\": \"$secret_key\", \"endpoint\": \"$endpoint\", \"region\": \"$region\", \"request_checksum_calculation\": \"$request_checksum_calculation\", \"response_checksum_validation\": \"$response_checksum_validation\", \"host\": \"$host_style\"}" $CONFIG_FILE

    echo "Profile $profile_name added to config.yaml"
}

# Function to create configs
create_configs() {
    # Write aws, rclone and mgc config
    config=$(yq eval '.' "$CONFIG_FILE")
    write_aws_config "$config"
    write_rclone_config "$config"
    write_mgc_configs "$config"
}

# Function to list remotes
list_remotes() {
    echo "Remotes:"
    yq eval '.remotes | keys | .[]' "$CONFIG_FILE"
}

# Function to install deps
install_deps() {
    echo "installing unzip..."
    sudo apt-get install unzip
    echo "installing yq..."
    # Verifica e instala o yq 
    sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
    sudo chmod +x /usr/bin/yq

    # Verifica privilégios de sudo e instala o rclone
    echo "installing rclone..."
    # 
    curl https://rclone.org/install.sh | bash

    # Verifica privilégios de sudo e instala o MGC (Multi-Cloud Gateway)
    echo "installing mgc..."
    # sudo -v
    sudo -v ; curl https://raw.githubusercontent.com/marmotitude/mgc-installer/main/install.sh | sudo bash

    # Baixa, descompacta e instala o AWS CLI v2
    echo "installing aws..."
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
}

# Function to delete a profile of config.yaml
profile_delete() {
    profile_name="$1"
    # Delete the entry on the config.yaml
    yq eval -i "del(.remotes.\"$profile_name\")" "$CONFIG_FILE"

    echo "Profile $profile_name deleted from $CONFIG_FILE"

    # Re-write the configs for AWS, Rclone and MGC
    config=$(yq eval '.' "$CONFIG_FILE")
    write_aws_config "$config"
    write_rclone_config "$config"
    write_mgc_configs "$config"
}

# Function to change a profile
profile_edit() {
    profile_name="$1"
    if [ -z "$profile_name" ]; then
        echo "Error: No profile name provided"
        exit 1
    fi

    # Check if profile exists
    if ! yq eval ".remotes | has(\"$profile_name\")" "$CONFIG_FILE"; then
        echo "Error: The profile '$profile_name' not exists"
        exit 1
    fi

    # Get the current values
    access_key=$(yq eval ".remotes.\"$profile_name\".access_key" "$CONFIG_FILE")
    secret_key=$(yq eval ".remotes.\"$profile_name\".secret_key" "$CONFIG_FILE")
    endpoint=$(yq eval ".remotes.\"$profile_name\".endpoint" "$CONFIG_FILE")
    region=$(yq eval ".remotes.\"$profile_name\".region" "$CONFIG_FILE")
    request_checksum_calculation=$(yq eval ".remotes.\"$profile_name\".request_checksum_calculation" "$CONFIG_FILE")
    response_checksum_validation=$(yq eval ".remotes.\"$profile_name\".response_checksum_validation" "$CONFIG_FILE")
    host_style=$(yq eval ".remotes.\"$profile_name\".host" "$CONFIG_FILE")

    # Prompt for new values, using current values as defaults
    read -rp "Enter new access key: " -e -i "$access_key" access_key
    read -rp "Enter new secret key: " -e -i "$secret_key" secret_key
    read -rp "Enter new endpoint: " -e -i "$endpoint" endpoint
    read -rp "Enter region (default us-east-1, current: $region): " -e -i "${region:-us-east-1}" region
    read -rp "Enter request_checksum_calculation (default WHEN_REQUIRED, current: $request_checksum_calculation): " -e -i "${request_checksum_calculation:-WHEN_REQUIRED}" request_checksum_calculation
    read -rp "Enter response_checksum_validation (default WHEN_REQUIRED, current: $response_checksum_validation): " -e -i "${response_checksum_validation:-WHEN_REQUIRED}" response_checksum_validation
    read -rp "Enter host style (default path, current: $host_style): " -e -i "${host_style:-path}" host_style

    # Append new remote to file config.yaml
    yq eval -i ".remotes.\"$profile_name\" = {\"access_key\": \"$access_key\", \"secret_key\": \"$secret_key\", \"endpoint\": \"$endpoint\", \"region\": \"$region\", \"host\": \"$host_style\"}" $CONFIG_FILE

    echo "Profile $profile_name edited in $CONFIG_FILE"

    # Re-write the configs for AWS, Rclone and MGC
    config=$(yq eval '.' "$CONFIG_FILE")
    write_aws_config "$config"
    write_rclone_config "$config"
    write_mgc_configs "$config"
}

# Function to show a remote details
show_remote_details() {
    profile_name="$1"
    if [ -z "$profile_name" ]; then
        echo "Error: No profile name provided"
        exit 1
    fi

    # Verificar se o perfil existe
    if ! yq eval ".remotes | has(\"$profile_name\")" "$CONFIG_FILE"; then
        echo "Error: The profile '$profile_name' not exists"
        exit 1
    fi

    echo "Remote details to '$profile_name':"
    yq eval ".remotes.\"$profile_name\"" "$CONFIG_FILE"
}

# Check if config.yaml exists, and create if necessary
if [ ! -f "$CONFIG_FILE" ]; then
    echo "config.yaml not found, creating with basic structure..."
    mkdir -p "$CONFIG_DIR"
    echo "remotes:" > "$CONFIG_FILE"
fi

# Manual of use on script
print_usage() {
    echo "Usage: s3config <command>"
    echo
    echo "Commands:"
    echo "  configure               Configure a new s3 profile"
    echo "  set <profile-name>      Set the s3 profile to use"
    echo "  create                  Write AWS,Rclone and MGC configurations"
    echo "  delete <profile-name>   Delete a profile"
    echo "  list                    List remotes"
    echo "  show <profile-name>     List remote details"
    echo "  install                 Install dependency YQ and clients aws/mgc/rclone in the latest version"
}

# Check which command was selected 
case "$1" in
    "configure")
        profile_configure
        # Recarregar a configuração após adicionar o novo perfil
        create_configs
        ;;
    "set")
        if [ -n "$2" ]; then
            export AWS_PROFILE="$2"
            echo "Profile aws set to $2"
            mgc workspace set "$2"
            echo "profile mgc set to $2"
        else
            echo "Error: No profile name provided"
            exit 1
        fi
        ;;
    "create")
        create_configs
        ;;
    "delete")
        if [ -n "$2" ]; then
            profile_delete "$2"
        else
            echo "Error: No profile name provided"
            exit 1
        fi
        ;;
    "list")
        list_remotes
        ;;
    "edit")
        if [ -n "$2" ]; then
            profile_edit "$2"
        else
            echo "Error: No profile name provided"
            exit 1
        fi
        ;;
    "show")
        show_remote_details "$2"
        ;;
    "install")
        install_deps
        ;;
        *)
        print_usage
        exit 1
        ;;
esac
