name: Build and Upload Debian Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build the project
        run: |
          mkdir -p s3config/DEBIAN
          echo "Package: s3config" > s3config/DEBIAN/control
          echo "Version: ${{ github.event.inputs.version }}" >> s3config/DEBIAN/control
          echo "Section: base" >> s3config/DEBIAN/control
          echo "Priority: optional" >> s3config/DEBIAN/control
          echo "Architecture: all" >> s3config/DEBIAN/control
          echo "Maintainer: Bruno Fernandes <bruno.fernandes1996@hotmail.com>" >> s3config/DEBIAN/control
          echo "Description: S3 Config is a software to create config files to AWS, Rclone and MGC" >> s3config/DEBIAN/control
          
          dpkg-deb --build s3config
        shell: bash

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3config.deb
          path: s3config.deb
